[package]
name = "bevy_invaders"
version = "0.1.0"
authors = ["ickk <git@ickk.io>"]
edition = "2018"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "71bf07f5c085b9c02cbe5337040337c3ed8b0002"}

[build-dependencies]
chrono = "0.4"
git2 = "0.13"
